### ISSUE TITLE
Task 13: Accounts UI Components

### ISSUE THREAD

**Issue by UdhayakumarThangavel** [iamneo-production/4e0b2c8f-dfc4-450c-8a31-412bcf206b58#75]
### Step 1: 
Create a Screen file called `AccountScreen` add the layout to get the header and sidebar and give the title as Accounts 

**Example** (AccountScreen.js)
```
import Layout from "../components/Layout";

export default function  AccountScreen(){
    return(
        <Layout title={"Accounts"} load={false}>
            <div>
                {/*
                    Code here
                */}
            </div>
        </Layout>
    )
}
```
### Step 2: 
Create a component file called `AccountHeader` add the appropriate contends.
the output should look like this.
![image](https://github.com/iamneo-production/4e0b2c8f-dfc4-450c-8a31-412bcf206b58/assets/60465112/180186b8-4dc7-4979-8068-821504176386)
### Step 3: 
Create a component file called `AccountFeature` add the appropriate contends.
the output should look like this.
![image](https://github.com/iamneo-production/4e0b2c8f-dfc4-450c-8a31-412bcf206b58/assets/60465112/59e80508-f6dd-4f41-9225-50ecc7ad305c)
### Step 4: 
Create a component file called `AccountList` add the appropriate contends.
the output should look like this.
![image](https://github.com/iamneo-production/4e0b2c8f-dfc4-450c-8a31-412bcf206b58/assets/60465112/3496f96e-b864-4c69-b930-1d6d3f2ecf54)
### Step 5: 
Add all the created components in Screen File and the output should look like this.

![image](https://github.com/iamneo-production/4e0b2c8f-dfc4-450c-8a31-412bcf206b58/assets/60465112/272e3175-7745-4ccb-b70d-b31fafae88e0)

### Step 6: 
Created a form called `AccountForm` for creating a new account. This component should include input fields for Account name, balance and Payment modes. The form should look like this.

![image](https://github.com/iamneo-production/4e0b2c8f-dfc4-450c-8a31-412bcf206b58/assets/60465112/6d60d7ac-b17b-4dbe-80d8-07ee5d7d188d)

### Folder Structure:
`/src/components/accounts/AccountHeader.js `
`/src/components/accounts/AccountFeature.js `
`/src/components/accounts/AccountList.js `
`/src/components/accounts/AccountForm.js `
`/src/screens/AccountScreen.js `

**Comment by Swetha2101** [comment]
Completed
